############################################################
#
#  服务配置
#
############################################################
server:
  servlet:
    context-path: /consumer
  port: 8002

############################################################
#
#  spring 与 lafla 整合
#
############################################################
spring:
  kafka:
    bootstrap-servers: 192.168.8.247:9092
    consumer:
      enable-auto-commit: false # 消息的签收机制：手工签收
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: earliest
      ## 序列化配置
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual # 手工签收
      concurrency: 5
